// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// atrDataDao is the data access object for the table hg_atr_data.
// You can define custom methods on it to extend its functionality as needed.
type atrDataDao struct {
	*internal.AtrDataDao
}

var (
	// AtrData is a globally accessible object for table hg_atr_data operations.
	AtrData = atrDataDao{internal.NewAtrDataDao()}
)

// Add your custom methods and functionality below.
