// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// balanceSheetDao is the data access object for the table hg_balance_sheet.
// You can define custom methods on it to extend its functionality as needed.
type balanceSheetDao struct {
	*internal.BalanceSheetDao
}

var (
	// BalanceSheet is a globally accessible object for table hg_balance_sheet operations.
	BalanceSheet = balanceSheetDao{internal.NewBalanceSheetDao()}
)

// Add your custom methods and functionality below.
