// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// bollDataDao is the data access object for the table hg_boll_data.
// You can define custom methods on it to extend its functionality as needed.
type bollDataDao struct {
	*internal.BollDataDao
}

var (
	// BollData is a globally accessible object for table hg_boll_data operations.
	BollData = bollDataDao{internal.NewBollDataDao()}
)

// Add your custom methods and functionality below.
