// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// cciDataDao is the data access object for the table hg_cci_data.
// You can define custom methods on it to extend its functionality as needed.
type cciDataDao struct {
	*internal.CciDataDao
}

var (
	// CciData is a globally accessible object for table hg_cci_data operations.
	CciData = cciDataDao{internal.NewCciDataDao()}
)

// Add your custom methods and functionality below.
