// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// internalEnterpriseHistoricalDataDao is an internal type for wrapping the internal DAO implementation.
type internalEnterpriseHistoricalDataDao = *internal.EnterpriseHistoricalDataDao

// enterpriseHistoricalDataDao is the data access object for the table hg_enterprise_historical_data.
// You can define custom methods on it to extend its functionality as needed.
type enterpriseHistoricalDataDao struct {
	internalEnterpriseHistoricalDataDao
}

var (
	// EnterpriseHistoricalData is a globally accessible object for table hg_enterprise_historical_data operations.
	EnterpriseHistoricalData = enterpriseHistoricalDataDao{
		internal.NewEnterpriseHistoricalDataDao(),
	}
)

// Add your custom methods and functionality below.
