// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// fastkDataDao is the data access object for the table hg_fastk_data.
// You can define custom methods on it to extend its functionality as needed.
type fastkDataDao struct {
	*internal.FastkDataDao
}

var (
	// FastkData is a globally accessible object for table hg_fastk_data operations.
	FastkData = fastkDataDao{internal.NewFastkDataDao()}
)

// Add your custom methods and functionality below.
