// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// financialIndicatorsMttDao is the data access object for the table hg_financial_indicators_mtt.
// You can define custom methods on it to extend its functionality as needed.
type financialIndicatorsMttDao struct {
	*internal.FinancialIndicatorsMttDao
}

var (
	// FinancialIndicatorsMtt is a globally accessible object for table hg_financial_indicators_mtt operations.
	FinancialIndicatorsMtt = financialIndicatorsMttDao{internal.NewFinancialIndicatorsMttDao()}
)

// Add your custom methods and functionality below.
