// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// financialIndicatorsDao is the data access object for the table hg_financial_indicators.
// You can define custom methods on it to extend its functionality as needed.
type financialIndicatorsDao struct {
	*internal.FinancialIndicatorsDao
}

var (
	// FinancialIndicators is a globally accessible object for table hg_financial_indicators operations.
	FinancialIndicators = financialIndicatorsDao{internal.NewFinancialIndicatorsDao()}
)

// Add your custom methods and functionality below.
