// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// flowOfFundsDao is the data access object for the table hg_flow_of_funds.
// You can define custom methods on it to extend its functionality as needed.
type flowOfFundsDao struct {
	*internal.FlowOfFundsDao
}

var (
	// FlowOfFunds is a globally accessible object for table hg_flow_of_funds operations.
	FlowOfFunds = flowOfFundsDao{internal.NewFlowOfFundsDao()}
)

// Add your custom methods and functionality below.
