// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// fundStockHoldingDao is the data access object for the table hg_fund_stock_holding.
// You can define custom methods on it to extend its functionality as needed.
type fundStockHoldingDao struct {
	*internal.FundStockHoldingDao
}

var (
	// FundStockHolding is a globally accessible object for table hg_fund_stock_holding operations.
	FundStockHolding = fundStockHoldingDao{internal.NewFundStockHoldingDao()}
)

// Add your custom methods and functionality below.
