// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// incomeStatementDao is the data access object for the table hg_income_statement.
// You can define custom methods on it to extend its functionality as needed.
type incomeStatementDao struct {
	*internal.IncomeStatementDao
}

var (
	// IncomeStatement is a globally accessible object for table hg_income_statement operations.
	IncomeStatement = incomeStatementDao{internal.NewIncomeStatementDao()}
)

// Add your custom methods and functionality below.
