// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// kdjDataDao is the data access object for the table hg_kdj_data.
// You can define custom methods on it to extend its functionality as needed.
type kdjDataDao struct {
	*internal.KdjDataDao
}

var (
	// KdjData is a globally accessible object for table hg_kdj_data operations.
	KdjData = kdjDataDao{internal.NewKdjDataDao()}
)

// Add your custom methods and functionality below.
