// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// internalKdjDataDao is an internal type for wrapping the internal DAO implementation.
type internalKdjDataDao = *internal.KdjDataDao

// kdjDataDao is the data access object for the table hg_kdj_data.
// You can define custom methods on it to extend its functionality as needed.
type kdjDataDao struct {
	internalKdjDataDao
}

var (
	// KdjData is a globally accessible object for table hg_kdj_data operations.
	KdjData = kdjDataDao{
		internal.NewKdjDataDao(),
	}
)

// Add your custom methods and functionality below.
