// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// kstDataDao is the data access object for the table hg_kst_data.
// You can define custom methods on it to extend its functionality as needed.
type kstDataDao struct {
	*internal.KstDataDao
}

var (
	// KstData is a globally accessible object for table hg_kst_data operations.
	KstData = kstDataDao{internal.NewKstDataDao()}
)

// Add your custom methods and functionality below.
