// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// macdDataDao is the data access object for the table hg_macd_data.
// You can define custom methods on it to extend its functionality as needed.
type macdDataDao struct {
	*internal.MacdDataDao
}

var (
	// MacdData is a globally accessible object for table hg_macd_data operations.
	MacdData = macdDataDao{internal.NewMacdDataDao()}
)

// Add your custom methods and functionality below.
