// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// momDataDao is the data access object for the table hg_mom_data.
// You can define custom methods on it to extend its functionality as needed.
type momDataDao struct {
	*internal.MomDataDao
}

var (
	// MomData is a globally accessible object for table hg_mom_data operations.
	MomData = momDataDao{internal.NewMomDataDao()}
)

// Add your custom methods and functionality below.
