// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// quarterlyProfitDao is the data access object for the table hg_quarterly_profit.
// You can define custom methods on it to extend its functionality as needed.
type quarterlyProfitDao struct {
	*internal.QuarterlyProfitDao
}

var (
	// QuarterlyProfit is a globally accessible object for table hg_quarterly_profit operations.
	QuarterlyProfit = quarterlyProfitDao{internal.NewQuarterlyProfitDao()}
)

// Add your custom methods and functionality below.
