// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// rsiDataDao is the data access object for the table hg_rsi_data.
// You can define custom methods on it to extend its functionality as needed.
type rsiDataDao struct {
	*internal.RsiDataDao
}

var (
	// RsiData is a globally accessible object for table hg_rsi_data operations.
	RsiData = rsiDataDao{internal.NewRsiDataDao()}
)

// Add your custom methods and functionality below.
