// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// shareholderCountDao is the data access object for the table hg_shareholder_count.
// You can define custom methods on it to extend its functionality as needed.
type shareholderCountDao struct {
	*internal.ShareholderCountDao
}

var (
	// ShareholderCount is a globally accessible object for table hg_shareholder_count operations.
	ShareholderCount = shareholderCountDao{internal.NewShareholderCountDao()}
)

// Add your custom methods and functionality below.
