// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// shareholderChangeDao is the data access object for the table hg_shareholder_change.
// You can define custom methods on it to extend its functionality as needed.
type shareholderChangeDao struct {
	*internal.ShareholderChangeDao
}

var (
	// ShareholderChange is a globally accessible object for table hg_shareholder_change operations.
	ShareholderChange = shareholderChangeDao{internal.NewShareholderChangeDao()}
)

// Add your custom methods and functionality below.
