// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// slowStochasticDataDao is the data access object for the table hg_slow_stochastic_data.
// You can define custom methods on it to extend its functionality as needed.
type slowStochasticDataDao struct {
	*internal.SlowStochasticDataDao
}

var (
	// SlowStochasticData is a globally accessible object for table hg_slow_stochastic_data operations.
	SlowStochasticData = slowStochasticDataDao{internal.NewSlowStochasticDataDao()}
)

// Add your custom methods and functionality below.
