// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// stockSupportResistanceDao is the data access object for the table hg_stock_support_resistance.
// You can define custom methods on it to extend its functionality as needed.
type stockSupportResistanceDao struct {
	*internal.StockSupportResistanceDao
}

var (
	// StockSupportResistance is a globally accessible object for table hg_stock_support_resistance operations.
	StockSupportResistance = stockSupportResistanceDao{internal.NewStockSupportResistanceDao()}
)

// Add your custom methods and functionality below.
