// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// stockSelfAiDao is the data access object for the table hg_stock_self_ai.
// You can define custom methods on it to extend its functionality as needed.
type stockSelfAiDao struct {
	*internal.StockSelfAiDao
}

var (
	// StockSelfAi is a globally accessible object for table hg_stock_self_ai operations.
	StockSelfAi = stockSelfAiDao{internal.NewStockSelfAiDao()}
)

// Add your custom methods and functionality below.
