// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// stockAiJudgmentDao is the data access object for the table hg_stock_ai_judgment.
// You can define custom methods on it to extend its functionality as needed.
type stockAiJudgmentDao struct {
	*internal.StockAiJudgmentDao
}

var (
	// StockAiJudgment is a globally accessible object for table hg_stock_ai_judgment operations.
	StockAiJudgment = stockAiJudgmentDao{internal.NewStockAiJudgmentDao()}
)

// Add your custom methods and functionality below.
