// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// stockListDao is the data access object for the table hg_stock_list.
// You can define custom methods on it to extend its functionality as needed.
type stockListDao struct {
	*internal.StockListDao
}

var (
	// StockList is a globally accessible object for table hg_stock_list operations.
	StockList = stockListDao{internal.NewStockListDao()}
)

// Add your custom methods and functionality below.
