// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// internalStockAllCodeDao is an internal type for wrapping the internal DAO implementation.
type internalStockAllCodeDao = *internal.StockAllCodeDao

// stockAllCodeDao is the data access object for the table hg_stock_all_code.
// You can define custom methods on it to extend its functionality as needed.
type stockAllCodeDao struct {
	internalStockAllCodeDao
}

var (
	// StockAllCode is a globally accessible object for table hg_stock_all_code operations.
	StockAllCode = stockAllCodeDao{
		internal.NewStockAllCodeDao(),
	}
)

// Add your custom methods and functionality below.
