// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// stockScoreMainDao is the data access object for the table hg_stock_score_main.
// You can define custom methods on it to extend its functionality as needed.
type stockScoreMainDao struct {
	*internal.StockScoreMainDao
}

var (
	// StockScoreMain is a globally accessible object for table hg_stock_score_main operations.
	StockScoreMain = stockScoreMainDao{internal.NewStockScoreMainDao()}
)

// Add your custom methods and functionality below.
