// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// stockBasicInfoDao is the data access object for the table hg_stock_basic_info.
// You can define custom methods on it to extend its functionality as needed.
type stockBasicInfoDao struct {
	*internal.StockBasicInfoDao
}

var (
	// StockBasicInfo is a globally accessible object for table hg_stock_basic_info operations.
	StockBasicInfo = stockBasicInfoDao{internal.NewStockBasicInfoDao()}
)

// Add your custom methods and functionality below.
