// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// valuationIndicatorsDao is the data access object for the table hg_valuation_indicators.
// You can define custom methods on it to extend its functionality as needed.
type valuationIndicatorsDao struct {
	*internal.ValuationIndicatorsDao
}

var (
	// ValuationIndicators is a globally accessible object for table hg_valuation_indicators operations.
	ValuationIndicators = valuationIndicatorsDao{internal.NewValuationIndicatorsDao()}
)

// Add your custom methods and functionality below.
