// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// williamsDataDao is the data access object for the table hg_williams_data.
// You can define custom methods on it to extend its functionality as needed.
type williamsDataDao struct {
	*internal.WilliamsDataDao
}

var (
	// WilliamsData is a globally accessible object for table hg_williams_data operations.
	WilliamsData = williamsDataDao{internal.NewWilliamsDataDao()}
)

// Add your custom methods and functionality below.
